### PR TITLE
fix: 🐛 handle undefined nodes

### LINKED ISSUE #246: Bug: Extraction error on Angular 21.1.0
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Is this a regression?

Yes

### Current behavior

`transloco-keys-manager extract` errors if using `@switch` statements in template that contain a transloco directive

> Extracting Template and Component Keys 🗝file:///Users/user/src/tkm-ng21.1/node_modules/.pnpm/@jsverse+transloco-keys-manager@7.1.0_typescript@5.9.3/node_modules/@jsverse/transloco-keys-manager/keys-builder/template/directive.extractor.js:12
>     for (const node of nodes) {
                       ^
> TypeError: nodes is not iterable
>    at traverse (file:///Users/user/src/tkm-ng21.1/node_modules/.pnpm/@jsverse+transloco-keys-manager@7.1.0_typescript@5.9.3/node_modules/@jsverse/transloco-keys-manager/keys-builder/template/directive.extractor.js:12:24)

`nodes` is `undefined` at that point.

### Expected behavior

The command goes through and doesn't error. Same code worked under Angular `21.0.9`

### Please provide a link to a minimal reproduction of the bug

https://github.com/jase88/tkm-ng21.1

and call `pnpm run i18n:extract`

### Transloco Config

```markdown
see repo
```

### Debug Logs

```markdown

```

### Please provide the environment you discovered this bug in

```markdown
Transloco: 8.2.0
Transloco Keys Manager: 7.1.0
Angular: 21.1.0
Node: 24.12.0
Package Manager: pnpm
OS:MacOS
```

### Additional context

_No response_

### I would like to make a pull request for this bug

No

### PR DESCRIPTION
**Pull request by medbenmakhlouf**
✅ Closes: #246

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/jsverse/transloco/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

```
[x] Yes
[] No
```

### CODE REVIEW

**Comment by medbenmakhlouf** [comment]
@shaharkazaz @cx-shahar-kazaz With Angular v21.1.0, we had a bug causing a loop on undefined nodes. I’ve fixed it, and I hope you can review it quickly. Thanks.

**Comment by jase88** [comment]
Your fix does resolve the crash in the CLI, but keys in the affected templates are no longer recognized. Looks like there is a breaking change in `@angular/compiler`

Maybe https://github.com/angular/angular/commit/640693da8e667c015662246152236585d9b24e7f

**Comment by medbenmakhlouf** [comment]
@jase, you’re right — I need to add test cases for the new switch syntax that introduces multi-case blocks.

@cx-shahar-kazaz  @shaharkazaz , unfortunately this does appear to be a breaking change introduced in Angular v21.1.0. I agree it’s frustrating for the community to see breakage alongside new features; ideally this would have landed as part of a major release. That said, in this PR I’ve added new test cases to cover the change, and all tests are now passing. I also had to improve some typings to prevent build failures.

Looking forward to your feedback... this should be good to go.

**Comment by medbenmakhlouf** [comment]
@jase88 , if you want an early test, here is the pack, you can install it like the following: 

``` json 
"@jsverse/transloco-keys-manager": "file:jsverse-transloco-keys-manager-7.2.0.tgz"
```
here is the build : 
[jsverse-transloco-keys-manager-7.2.0.tgz](https://github.com/user-attachments/files/24691844/jsverse-transloco-keys-manager-7.2.0.tgz)

let's us know your feedback ;)

**Comment by jase88** [comment]
@medbenmakhlouf thanks for your effort!

looking good on my project. now all keys are detected and no error occurs :)

File: src/keys-builder/template/structural-directive.extractor.ts [hunk 1]
```diff
@@ -173,7 +173,7 @@ function resolveMetadata(node: TmplAstTemplate): ContainerMetaData[] {
     let read = node.attributes.find(isPrefixAttr)?.value;
     if (!read) {
       const ast = (node.inputs.find(isPrefixAttr)?.value as ASTWithSource)?.ast;
-      if (isLiteralExpression(ast)) {
+      if (isLiteralExpression(ast) && typeof ast.value === 'string') {
```
Comment (shaharkazaz) [inline src/keys-builder/template/structural-directive.extractor.ts]: Can you share why we need this change? Also, please use isString from validators.

File: src/keys-builder/template/utils.ts [hunk 2]
```diff
@@ -170,7 +182,7 @@ export function resolveKeysFromLiteralMap(node: LiteralMap): string[] {
   let keys: string[] = [];
 
   for (let i = 0; i < node.values.length; i++) {
-    const { key } = node.keys[i];
+    const { key } = node.keys.filter(k=> k.kind === 'property')[i];
```
Comment (shaharkazaz) [inline src/keys-builder/template/utils.ts]: Can you share why do we need this change?

File: src/keys-builder/utils/resolvers.utils.ts [hunk 3]
```diff
@@ -13,6 +15,7 @@ export function resolveAliasAndKey(
    * {{ 'scopeAlias.title' | transloco }}
    *
    */
+  if (typeof key !== 'string') return ['', null];
```
Comment (shaharkazaz) [inline src/keys-builder/utils/resolvers.utils.ts]: Please use isString

**Review by shaharkazaz — COMMENTED** [review]
Thanks for the PR!

**Comment by shaharkazaz** [comment]
@medbenmakhlouf Please also pull master

File: src/keys-builder/template/structural-directive.extractor.ts (hunk 1 above)
Comment (medbenmakhlouf) [reply src/keys-builder/template/structural-directive.extractor.ts]: @shaharkazaz Prior to v21.1, LiteralPrimitive had a value type of `any`, but this was updated in a recent Angular PR (see here: [https://github.com/angular/angular/pull/66206](https://github.com/angular/angular/pull/66206/changes#diff-1002bdc266028e1c303492a63ed5990124b8fd29a8f87098d07f86c0519d47f0R199). Previously, the compiler didn't flag value types, but because we only treat LiteralExpression as a string in our case, I am adding this explicit type check to satisfy the new constraints.

File: src/keys-builder/template/utils.ts (hunk 2 above)
Comment (medbenmakhlouf) [reply src/keys-builder/template/utils.ts]: Same reasoning here. Angular introduced two subtypes for node.keys via the `LiteralMapKey` union type (`LiteralMapPropertyKey` | `LiteralMapSpreadKey`).

As shown in the definitions below, we need to distinguish between them:

``` ts
export interface LiteralMapPropertyKey {
  kind: 'property';
  key: string;
  // ...
}

export interface LiteralMapSpreadKey { 
kind: 'spread'; 
// ... 
}
```

I added the filter to check for `kind: 'property'` to ensure we are only processing valid properties, keeping this compatible with our previous logic (reference: [Angular Source](https://github.com/angular/angular/blob/5d46554e3fe8b64c5fefc7a8ce891c179741977e/packages/compiler/src/expression_parser/ast.ts#L241))

Comment (shaharkazaz) [reply src/keys-builder/template/utils.ts]: I'm merging this as is since we want the fix ASAP, but notice that this is a classic case to add it as a type guard and match the pattern in the code (`isLiteralMapPropertyKey`)

File: src/keys-builder/template/utils.ts [hunk 4]
```diff
@@ -105,7 +106,8 @@ export function isBlockWithChildren(
     node instanceof TmplAstDeferredBlockPlaceholder ||
     node instanceof TmplAstForLoopBlockEmpty ||
     node instanceof TmplAstIfBlockBranch ||
-    node instanceof TmplAstSwitchBlockCase
+    node instanceof TmplAstSwitchBlockCase ||
+    node instanceof TmplAstSwitchBlockCaseGroup
```
Comment (shaharkazaz) [inline src/keys-builder/template/utils.ts]: On the one had TmplAstSwitchBlockCase is removed from BlockNode type but on the other we are still checking it here.
Can you explain the difference?

File: src/keys-builder/template/directive.extractor.ts [hunk 5]
```diff
@@ -97,7 +98,7 @@ function resolveKey(ast: OrArray<AST | string>): string[] {
         return resolveKey(expression.expression);
       }
     })
-    .filter(Boolean)
+    .filter((key) => key !== undefined && key !== null && (isString(key) || Array.isArray(key)))
```
Comment (shaharkazaz) [inline src/keys-builder/template/directive.extractor.ts]:
```suggestion
    .filter((key) => notNil(key) && (isString(key) || Array.isArray(key)))
```

File: src/keys-builder/template/utils.ts (hunk 2 above)
Comment (medbenmakhlouf) [reply src/keys-builder/template/utils.ts]: this is done!

File: src/keys-builder/template/utils.ts (hunk 4 above)
Comment (medbenmakhlouf) [reply src/keys-builder/template/utils.ts]: Good catch. You’re right, `TmplAstSwitchBlockCase` is no longer part of `BlockNode`, and this check is leftover. It has no impact since all logic now relies on `TmplAstSwitchBlockCaseGroup`. I’ll remove it.

File: src/keys-builder/template/directive.extractor.ts (hunk 5 above)
Comment (medbenmakhlouf) [reply src/keys-builder/template/directive.extractor.ts]: done

**Review by shaharkazaz — APPROVED** [review]
